#!/bin/sh

# Create user and group
addgroup -g ${GID} dokuwiki && adduser -h /data -s /bin/sh -D -G dokuwiki -u ${UID} dokuwiki

# Set permissions
chown -R dokuwiki:dokuwiki /data /var/run/php-fpm.sock /var/lib/nginx /tmp

# RUN !
supervisord -c /etc/supervisor/supervisord.conf
