language: generic

env:
  global:
    - DOCKER_USERNAME=bxggs
    - DEFAULT_DOCKER_TAG=latest
  jobs:
    - DOCKER_IMAGE=aria2 RELATIVE_PATH=aria2
    - DOCKER_IMAGE=autosub RELATIVE_PATH=autosub
    - DOCKER_IMAGE=markserv RELATIVE_PATH=markserv
    - DOCKER_IMAGE=md-to-pdf RELATIVE_PATH=md-to-pdf
    - DOCKER_IMAGE=openssl RELATIVE_PATH=pirate-get
    - DOCKER_IMAGE=pywal RELATIVE_PATH=pywal
    - DOCKER_IMAGE=youtube-dl RELATIVE_PATH=youtube-dl

services:
  - docker

before_script:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      export DOCKER_TAG=$DEFAULT_DOCKER_TAG;
    else
      export DOCKER_TAG=$(echo "$TRAVIS_BRANCH" | awk '{ gsub("/", "-"); print $0 }');
    fi
  - docker build -t "$DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG" "$RELATIVE_PATH"

deploy:
  provider: script
  script: bash -c 'echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push "$DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG"'
  on:
    all_branches: true
